FORMAT: 1A
HOST: https://api.example.com

# REST API Documentation

# Group Users

## Users [/users]
<!-- include(requests/get-users.md) -->
<!-- include(requests/post-user.md) -->

<!-- include(requests/get-user.md) -->
